"""
Django settings for note project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8hd$&^^h=9(bl7eku3ogc&7*-j!ib9pi0!6x=f&8_x01v&efgu"
# 聊天機器人
LINE_CHANNEL_SECRET="bdfe18d4be5f83c677822470e0b3e94b"
LINE_CHANNEL_TOKEN="IK0kvlhTjih8WMWpkzL9mDkYVlnc1Tus1IRrRTe8VZY+VYPaOmJCEkOyUzrkd5k2S0TKGT9zbNixOf1vID7h7d8/ZS57v15bU9KD6Ao1krjmh2on8n/+zd8e+Viw9qCIiGVaUpWundFFW0ewcZ5hPwdB04t89/1O/w1cDnyilFU="
# SECURITY WARNING: don't run with debug turned on in production!
# 發到雲端更改為False
DEBUG = True

# 發到雲端更改為'*'
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mynote",
    "bot",    
    'django_bootstrap5',
    'phonenumber_field',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]
# 快取的設定
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         'LOCATION': 'my_table_name',
#     }
# }
# CACHE_MIDDLEWARE_SECONDS = 5  # 每個頁面應該被暫存的秒數，預設值600s

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 使用數據庫保存 session

ROOT_URLCONF = "note.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR,'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "note.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR,'static'),)# 或其他存放静态文件的目录

SESSION_COOKIE_AGE = 0.5*60*60
django_heroku.settings(locals())
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email發送
# 申請密碼：google帳號管理帳號>應用程式密碼
# paklkfmzlnijaave
# btounrmwmvmswqya
EMAIL_HOST = "smtp.gmail.com"

EMAIL_HOST_USER = "cji3xu06"

EMAIL_HOST_PASSWORD = "btounrmwmvmswqya"

EMAIL_PORT = "465"

EMAIL_USE_SSL = "True"

ADMINS = (('cji3xu06', 'cji3xu06@gmail.com'),)

MANAGERS = (('cji3xu06', 'cji3xu06@gmail.com'),)
