# Generated by Django 4.2.16 on 2024-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creatuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("randomnumber", models.CharField(max_length=50)),
                ("chickemail", models.BooleanField()),
            ],
            options={
                "db_table": "userinfo",
            },
        ),
        migrations.CreateModel(
            name="Notedatas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booktype", models.CharField(max_length=50, verbose_name="書本類型")),
                ("bookname", models.CharField(max_length=100, verbose_name="書名")),
                ("author", models.CharField(max_length=50, verbose_name="作者")),
                ("type_url", models.URLField(verbose_name="分類連結")),
                ("bookurl", models.URLField(verbose_name="書本連結")),
                ("authorurl", models.URLField(verbose_name="作者連結")),
                ("imageurl", models.URLField(verbose_name="圖片連結")),
                ("keep", models.PositiveIntegerField(verbose_name="收藏人數")),
                ("watch", models.PositiveIntegerField(verbose_name="觀看人數")),
            ],
            options={
                "db_table": "noteinfo",
            },
        ),
        migrations.CreateModel(
            name="Userlike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("bookname", models.CharField(max_length=100, verbose_name="書名")),
            ],
            options={
                "db_table": "userlike",
            },
        ),
    ]
