# Generated by Django 4.2.16 on 2024-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookandUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urlname", models.CharField(max_length=50)),
                ("booktype", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "bktypeurl",
            },
        ),
    ]
