# Generated by Django 4.2.16 on 2024-09-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0003_donloadbookanduser_remove_notedatas_type_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notedatas",
            new_name="NoteInfo",
        ),
    ]
