# Generated by Django 4.2.16 on 2024-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0004_rename_notedatas_noteinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="sitoNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booktype", models.CharField(max_length=50, verbose_name="書本類型")),
                ("bookname", models.CharField(max_length=100, verbose_name="書名")),
                ("bookurl", models.URLField(verbose_name="書本連結")),
                ("author", models.CharField(max_length=50, verbose_name="作者")),
                ("imageurl", models.URLField(verbose_name="圖片連結")),
            ],
            options={
                "db_table": "sitonoteinfo",
            },
        ),
        migrations.RenameModel(
            old_name="NoteInfo",
            new_name="Notedatas",
        ),
    ]
