# Generated by Django 4.2.16 on 2024-10-07 14:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0005_sitonote_rename_noteinfo_notedatas"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("birthday", models.DateField(help_text="user birthdate")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "personalinfo",
            },
        ),
    ]
