# Generated by Django 4.2.16 on 2024-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0008_alter_personalinformation_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="birthday",
            field=models.DateField(blank=True, help_text="user birthdate", null=True),
        ),
    ]
