# Generated by Django 4.2.16 on 2024-10-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0011_alter_personalinformation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
