# Generated by Django 4.2.16 on 2024-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0013_profile_alter_personalinformation_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="picfilename",
        ),
    ]
