# Generated by Django 4.2.16 on 2024-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0014_rename_name_profile_picfilename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlike",
            name="bookname",
            field=models.CharField(max_length=100, unique=True, verbose_name="書名"),
        ),
    ]
