# Generated by Django 4.2.16 on 2024-10-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0017_alter_userlike_bookname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donloadbookanduser",
            name="bookname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.notedatas",
                to_field="bookname",
                verbose_name="書名",
            ),
        ),
        migrations.AlterField(
            model_name="userlike",
            name="bookname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.notedatas",
                to_field="bookname",
                verbose_name="書名",
            ),
        ),
    ]
