# Generated by Django 4.2.16 on 2024-10-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0018_alter_donloadbookanduser_bookname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donloadbookanduser",
            name="bookname",
        ),
        migrations.RemoveField(
            model_name="userlike",
            name="bookname",
        ),
        migrations.AddField(
            model_name="donloadbookanduser",
            name="bookurl",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.notedatas",
                to_field="bookurl",
                verbose_name="書本連結",
            ),
        ),
        migrations.AddField(
            model_name="userlike",
            name="bookurl",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.notedatas",
                to_field="bookurl",
                verbose_name="書本連結",
            ),
        ),
        migrations.AlterField(
            model_name="notedatas",
            name="bookname",
            field=models.CharField(max_length=100, verbose_name="書名"),
        ),
        migrations.AlterField(
            model_name="notedatas",
            name="bookurl",
            field=models.URLField(
                default="https://example.com/default",
                unique=True,
                verbose_name="書本連結",
            ),
        ),
    ]
