# Generated by Django 4.2.16 on 2024-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0019_remove_donloadbookanduser_bookname_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userlike",
            constraint=models.UniqueConstraint(
                fields=("user", "bookurl"), name="unique_user_bookurl"
            ),
        ),
    ]
