# Generated by Django 4.2.16 on 2024-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0022_predrecommendbook_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDonloadKeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("keyword", models.CharField(max_length=50)),
                ("imgurl", models.URLField(verbose_name="圖片連結")),
                ("bookurl", models.URLField(verbose_name="書本連結")),
                ("author", models.CharField(max_length=50, verbose_name="作者")),
            ],
            options={
                "db_table": "userdownload_keyword",
            },
        ),
    ]
