# Generated by Django 4.2.16 on 2024-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0023_userdonloadkeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdonloadkeyword",
            name="bookname",
            field=models.CharField(default=2, max_length=50, verbose_name="書名"),
            preserve_default=False,
        ),
    ]
