# Generated by Django 4.2.16 on 2024-10-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0027_donloadbookanduser_unique_dowl_user_bookurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notedatas",
            name="bookurl",
            field=models.URLField(unique=True, verbose_name="書本連結"),
        ),
    ]
