# Generated by Django 4.2.16 on 2024-10-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0028_alter_notedatas_bookurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatuser",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.creatuser",
                to_field="email",
                unique=True,
                verbose_name="使用者信箱",
            ),
        ),
        migrations.AlterField(
            model_name="userlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.personalinformation",
                to_field="email",
                verbose_name="使用者信箱",
            ),
        ),
    ]
