# Generated by Django 4.2.16 on 2024-10-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0030_alter_personalinformation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donloadbookanduser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.personalinformation",
                to_field="email",
                verbose_name="使用者信箱",
            ),
        ),
        migrations.AlterField(
            model_name="predrecommendbook",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mynote.personalinformation",
                to_field="email",
                verbose_name="使用者信箱",
            ),
        ),
    ]
