# Generated by Django 4.2.16 on 2024-10-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0031_alter_donloadbookanduser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatuser",
            name="chickemail",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
