# Generated by Django 4.2.16 on 2024-10-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0037_alter_notedatas_bookstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notedatas",
            name="bookstate",
        ),
    ]
