# Generated by Django 4.2.16 on 2024-10-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0038_remove_notedatas_bookstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="notedatas",
            name="bookstate",
            field=models.BooleanField(blank=True, null=True, verbose_name="完本記錄"),
        ),
    ]
