# Generated by Django 4.2.16 on 2024-10-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynote", "0039_notedatas_bookstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notedatas",
            name="bookstate",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="完本記錄"
            ),
        ),
    ]
