# Generated by Django 4.2.16 on 2024-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Linebotuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=128)),
                ("step", models.CharField(max_length=20)),
                ("booktype", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "linebotinfo",
            },
        ),
    ]
