# Generated by Django 4.2.16 on 2024-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linebotuser",
            name="user",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
