# Generated by Django 4.2.16 on 2024-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_linebotuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linebotuser",
            name="step",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
