# Generated by Django 4.2.16 on 2024-10-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_alter_linebotuser_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linebotuser",
            name="step",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
