# Generated by Django 4.2.16 on 2024-10-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_alter_linebotuser_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="linebotuser",
            name="updatasstr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="linebotuser",
            name="booktype",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
